---
dependency:
  name: galaxy
role_name_check: 1
driver:
  name: docker
#lint:
#  name: yamllint
#  options:
#  config-file: molecule/default/yamllint.yml
platforms:
  - name: Ubuntu 
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

  - name: Rocky 
    image: "geerlingguy/docker-rockylinux8-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true  

provisioner:
  name: ansible
  #lint:
  #  name: ansible-lint
verifier:
  name: testinfra
  #lint:
  #  name: flake8